app = "helium-localization-api"
primary_region = "sjc"  # San Jose, CA - you can change this to your preferred region

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  SUPABASE_URL = ""  # You'll need to set this in Fly.io dashboard
  SUPABASE_ANON_KEY = ""  # You'll need to set this in Fly.io dashboard

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"] 